AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/VariableNumber:
  EnforcedStyle: snake_case

Metrics/BlockLength: # testing blocks usually have more than 25 lines
  Exclude:
    - spec/**/*
